apiVersion: v1
kind: Service
metadata:
  name: myapp-loadbalancer
  namespace: efs_ns
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30002
  selector:
    type: front-end
